### ISSUE TITLE
Request: Any way I can remove the default date?

### ISSUE THREAD

**Issue by gacrestani** [swsnr/gnome-shell-extension-utc-clock#29]

**Comment by swsnr** [comment]
@gacrestani I see you closed this issue again, so I guess this is no longer relevant, but for the record I'd like to point out that you'd have to make a pull request, as I have no use for this feature myself.

**Comment by gacrestani** [comment]
> @gacrestani I see you closed this issue again, so I guess this is no longer relevant, but for the record I'd like to point out that you'd have to make a pull request, as I have no use for this feature myself.

That is very reasonable! Thank you for creating a great extension.
